### ISSUE TITLE
Missing Schematics

### ISSUE THREAD

**Issue by SuneBielefeldt** [AnaviTechnology/anavi-docs#24]
**Missing Schematics**

I miss a drawing of how the hardware is screwed together. 
Can you add a schematics as an image file to Github?

**Comment by leon-anavi** [comment]
Hi @SuneBielefeldt,

The schematics of each board are available as part of the whole KiCad project available at GitHub. The name of the repository follows the naming convention with lowercase letters and dash instead of space, for example:
* ANAVI Thermometer https://github.com/AnaviTechnology/anavi-thermometer
* ANAVI Gas Detector https://github.com/AnaviTechnology/anavi-gas-detector
* ANAVI Light Controller  https://github.com/AnaviTechnology/anavi-light-controller

Various step by step guides, including assembly guides for some of the kits are available at my YouTube channel: https://www.youtube.com/channel/UC4OQ5CQw8kuucCM8mG8woOQ

For which board exactly is the question? Let me know and I will point you to the exact links for it.

Thanks,
Leon
